IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.1.6
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc_lfe_vac
PROJECT_PATH := ../../plc_lfe_vac/plc_lfe_vac.tsproj
PLC = plc_lfe_vac

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
