IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/v0.1.5
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = PLC_LFE_VAC
PROJECT_PATH := ../../PLC_LFE_VAC/PLC_LFE_VAC.tsproj
PLC = PLC_LFE_VAC

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
