<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PRG_Section_1" Id="{49021430-2479-452d-9fb0-1e4b70e05342}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Section_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_Section_1">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>